import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' }); const pg = await b.newPage({ viewport: { width: 1700, height: 950 } }); const errs = [];
pg.on('pageerror', e => errs.push(e.stack.split('\n').slice(0, 3).join(' | ')));
await pg.route(/mlbstatic|statsapi|nhle|espn|githubusercontent/, r => r.abort());
await pg.goto('http://localhost:8300/nfl/index.html#play'); await pg.waitForTimeout(1500);
await pg.evaluate(() => { const b = document.querySelector('[data-mode=SPECTATOR]'); if (b) { b.click(); setTimeout(() => document.querySelector('[data-start]')?.click(), 150); } }); await pg.waitForTimeout(3000);
await pg.click('#zoomSeg [data-zoom="full"]'); await pg.waitForTimeout(1500); await pg.screenshot({ path: process.argv[2] + '/nfl_stands.png' });
await pg.click('#simEndBtn'); await pg.waitForSelector('.fin-overlay.show', { timeout: 120000 }); await pg.waitForTimeout(800);
await pg.screenshot({ path: process.argv[2] + '/nfl_final.png' });
console.log('errors', errs); await b.close();
