export const ROSTER_URL='https://github.com/nflverse/nflverse-data/releases/download/rosters/roster_2026.csv';
export const ALT_ROSTER_URL='https://github.com/nflverse/nflverse-data/releases/download/rosters/roster_2026.csv?raw=1';
export function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[]}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const head=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[h,(r[i]??'').trim()]))) }
function normalizeTeam(t){return t==='LAR'?'LA':t==='JAC'?'JAX':t==='WSH'?'WAS':t}
export function normalizePlayer(r){const birth=r.birth_date||'';let age=null;if(birth){const d=new Date(birth+'T00:00:00Z');if(!Number.isNaN(d.getTime())){const now=new Date('2026-10-06T12:00:00Z');age=now.getUTCFullYear()-d.getUTCFullYear()-((now.getUTCMonth()<d.getUTCMonth()||(now.getUTCMonth()===d.getUTCMonth()&&now.getUTCDate()<d.getUTCDate()))?1:0)}}return{...r,team:normalizeTeam(r.team),jersey_number:r.jersey_number||'',full_name:r.full_name||`${r.first_name||''} ${r.last_name||''}`.trim(),position:(r.position||r.depth_chart_position||'ATH').toUpperCase(),college:r.college||'Não informado',headshot_url:r.headshot_url||'',age,years_exp:Number(r.years_exp||0),height:Number(r.height||0),weight:Number(r.weight||0)}}
export async function fetchRoster(){let last;for(const url of [ROSTER_URL,ALT_ROSTER_URL]){try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const text=await res.text();const rows=parseCSV(text).map(normalizePlayer).filter(p=>p.full_name&&p.team);if(rows.length<1000)throw new Error('Roster recebido parece incompleto');return rows}catch(e){last=e}}throw last||new Error('Falha ao baixar roster')}
export function playerPhoto(p){if(p.headshot_url)return p.headshot_url;if(p.espn_id)return `https://a.espncdn.com/i/headshots/nfl/players/full/${p.espn_id}.png`;return ''}
export function logoUrl(team){return `https://a.espncdn.com/i/teamlogos/nfl/500/${team.espn}.png`}
export function initials(name='?'){return name.split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase()||'?'}
export function fallbackDataUri(name='?'){const i=initials(name);return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="100%" height="100%" fill="#203047"/><circle cx="80" cy="58" r="31" fill="#8aa0b9"/><path d="M28 154c8-38 30-55 52-55s44 17 52 55" fill="#8aa0b9"/><text x="80" y="149" font-family="Arial" font-size="24" fill="#0b1119" text-anchor="middle" font-weight="700">${i}</text></svg>`)}`}
