import {makeRatings,overall} from './ratings.js';
function pick(players, positions, n){const pool=players.filter(p=>positions.includes(p.position)).map(p=>{const r=makeRatings(p);return{p,r,o:overall(p,r)}}).sort((a,b)=>b.o-a.o);return pool.slice(0,n).map(x=>x.p)}
function fillDistinct(base,all,n){const ids=new Set(base.map(p=>p.gsis_id||p.full_name));for(const p of all){if(base.length>=n)break;const id=p.gsis_id||p.full_name;if(!ids.has(id)){base.push(p);ids.add(id)}}return base}
export function buildLineups(roster,offTeam,defTeam){const off=roster.filter(p=>p.team===offTeam&&['ACT','RES','DEV','INA'].includes(p.status||'ACT'));const def=roster.filter(p=>p.team===defTeam&&['ACT','RES','DEV','INA'].includes(p.status||'ACT'));let offense=[...pick(off,['QB'],1),...pick(off,['RB','FB'],1),...pick(off,['WR'],3),...pick(off,['TE'],1),...pick(off,['C','G','T','OT','OG','OL'],5)];let defense=[...pick(def,['DE','DT','NT','DL'],4),...pick(def,['LB','ILB','OLB','EDGE'],3),...pick(def,['CB','DB','S','FS','SS'],4)];return{offense:fillDistinct(offense,off,11),defense:fillDistinct(defense,def,11)}}
const formations={off:[[44,50],[38,42],[38,58],[31,35],[31,50],[31,65],[50,31],[50,39],[50,47],[50,55],[50,63]],def:[[56,35],[56,45],[56,55],[56,65],[63,35],[63,50],[63,65],[70,35],[70,45],[70,55],[70,65]]};
export function initialEntities(lineups){return [...lineups.offense.map((p,i)=>({p,side:'off',x:formations.off[i]?.[0]||40,y:formations.off[i]?.[1]||50})),...lineups.defense.map((p,i)=>({p,side:'def',x:formations.def[i]?.[0]||60,y:formations.def[i]?.[1]||50}))]}
function avg(list, keys){if(!list.length)return 100;let s=0,n=0;for(const p of list){const r=makeRatings(p);for(const k of keys){s+=r[k]||100;n++}}return s/n}
export function resolvePlay(lineups,type,down,distance){const O=lineups.offense,D=lineups.defense;const pass=avg(O,['throwingPower','shortAccuracy','mediumAccuracy','deepAccuracy','routeRunning','catching','awareness']);const rush=avg(O,['speed','acceleration','runBlock','blockStrength','carrying','vision']);const defense=avg(D,['tackling','playRecognition','runDefense','zoneCoverage','manCoverage','passRush']);const rand=(Math.random()-.5)*34;let yards=0,turnover=false,text='';if(type==='pass'){yards=Math.round((pass-defense)/8+6+rand/3);if(Math.random()<Math.max(.035,(defense-pass+80)/1200)){turnover=true;text='Interceptação!'}else if(Math.random()<.27){yards=0;text='Passe incompleto'}else text=`Passe completo para ${yards} jardas`}else if(type==='deep'){yards=Math.round((pass-defense)/6+17+rand/2);if(Math.random()<.12){turnover=true;text='Interceptação em passe profundo'}else if(Math.random()<.48){yards=0;text='Passe profundo incompleto'}else text=`Conexão profunda de ${yards} jardas`}else{yards=Math.round((rush-defense)/10+4+rand/5);if(Math.random()<.025){turnover=true;text='Fumble perdido!'}else text=`Corrida de ${yards} jardas`}yards=Math.max(-12,Math.min(75,yards));return{yards,turnover,text,firstDown:yards>=distance,touchdown:yards>=Math.max(distance,20)&&Math.random()<.16}}
export function animateTargets(entities,type,progress){return entities.map((e,i)=>{let x=e.x,y=e.y;if(e.side==='off'){if(i===0){x+=type==='run'?2:Math.min(5,progress*4)}else if(i>=1&&i<=5){const spread=(i-3)*8;y+=spread*progress;x+=type==='run'?(i===1?progress*12:progress*4):progress*(12+(i%2)*8)}else{x+=progress*2}}else{x-=progress*(4+(i%3));if(i>6)y+=(i%2?1:-1)*progress*5}return{...e,x,y}})}
